Avatar
talrejah02/component-library pull request #2
Opened 2022-02-11 20:50 UTC by talrejah02

Please review, suggestion's are welcomed.

2022-02-17 23:03 UTC, ScoobyDubeyDo requested changes

2022-02-17 23:03 UTC, ScoobyDubeyDo commented on components/Avatar/avatar.css
> +}
please avoid applying styles to the body itself.

2022-02-17 23:03 UTC, ScoobyDubeyDo commented on components/common-css/container.css
> +padding-left: 1rem !important;
Try avoid using !important

2022-02-17 23:23 UTC, talrejah02 commented on components/Avatar/avatar.css
> +}
okay sure thanks

2022-02-18 04:48 UTC, manojkumar8400 approved these changes
looks good.

2022-02-18 06:13 UTC, kshitijthatte approved these changes

2022-02-18 06:13 UTC, kshitijthatte commented on components/Avatar/avatar.css
> +
As recommended by @aman-can , avoid using style directly on HTML tags. Also, you've already styled body in style.css

2022-02-21 08:42 UTC, merged